version: '3.8'

services:
  valkey:
    image: valkey/valkey
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "sh", "-c", "valkey-cli ping || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
